#!/usr/bin/env bash
# Display information about subdomains

Sub_Info ()
{
    digExtract=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tr '\n' ' ')
    echo "$2 $digExtract" | awk '{print "The subdomain " $1 " is a " $8 " record and points to " $9}'
}
if [ $# -eq 1 ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"
    do
        Sub_Info $1 $subdomain
    done
else
        Sub_Info $1 $2
fi
