#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
sed -i '/listen 80 default_server;/rewrite ^/redirect_me https://www.youtube.com/ permanent;\n' /etc/nginx/sites-available/default
service nginx reload
