#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx

sed -i '/listen 80 default_server;/a rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;\nlocation /custom_404.html {\n\tinternal;\n}\n' /etc/nginx/sites-available/default
sudo service nginx start
