#!/usr/bin/env bash
# Configures a HAproxy load-balancer
apt-get update
apt-get -y install haproxy
sed -i '/errorfile 504/a listen holberton02cn0x' /etc/haproxy/haproxy.cfg
sed -i '/listen holberton02cn0x/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 546-web-01 104.196.55.234:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 546-web-01 104.196.55.234:80 check/a         server 546-web-02 35.229.108.9:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy restart
