#!/usr/bin/env bash
# Display username, user id and home directory for each line in /etc/passwd

input="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
