#!/usr/bin/env bash
# Displays "Holberton School" 9 out of 10 times
# On the 9th time, display "Hi"

i=0
while [ $i -lt 10 ]; do
      echo "Holberton School"
      if [ $i -eq 8 ]; then
      	 echo "Hi"
      fi
      let i=i+1
done
