#!/usr/bin/env bash
# Display "Holberton School" 8 of 10 times
# on 4, displays "bad luck", on 8, "good luck"

i=0
while [ $i -lt 10 ]; do
      if [ $i -eq 3 ]; then
      	 echo "bad luck"
      elif [ $i -eq 7 ]; then
      	 echo "good luck"
      else
	 echo "Holberton School"
      fi
      let i=i+1
done
