#!/usr/bin/env bash
# Marks numbers from 0-20 with superstitions associated

i=1
while [ $i -le 20 ]; do
      echo $i
      case $i in
      4)
	echo "bad luck from China" ;;
      9)
	echo "bad luck from Japan" ;;
      17)
	echo "bad luck from Italy" ;;
      esac
      let i=i+1
done
